import type { Metadata } from "next";
import {Avenir} from "@/helpers/fonts";
import "./globals.css";
import Navbar from "@/component/navbar/navbar.component";
import Footer from "@/component/footer/footer.component";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Avenir.variable}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
